server:
  port: 8443
  redirect:
    from: 80
    to: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/multishop.p12
    key-store-password: AsadMasad@1366
    key-alias: multishop
    enabled: true
debug:
  tenant:
    if-null: vavishka.piana.ir
login:
  redirect:
    url: https://piana.ir:8443
